title: Om Gulshan
logo: /assets/img/passport size photo.png
description: || Actively Seeking New Opportunities for Data Analyst Role ||BRANCH COORDINATOR Traning and placement cell ||Dsa fellow at nextleap||Finance associate trainee at invact metaversity||
show_downloads: false
theme: jekyll-theme-minimal
